project:  
  type: website
  output-dir: .                                                       
                                                                          
website:                                                                  
  title: "CM L1"                                        
  site-url: "https://fannyollivier.github.io/cours"
                                                                          
format:                                                                   
  revealjs:
   multiplex: true